# Tank Monitor Console Simulator -- a training simulator for TLS-350
# compatible tank monitor consoles.
# Copyright (C) 2026 Verbose Software
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. It is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License (LICENSE) for more details.
"""Write the Windows VERSIONINFO resource PyInstaller stamps on the .exe.

The version, the publisher and the product name all come from the package
itself, so the number in the file's Properties dialog is the same one the
About box shows and there is one place to change it. Run from the repo root:

    python packaging/make_version_info.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tls350sim import APP_NAME, PUBLISHER, __version__

parts = (__version__.split(".") + ["0", "0", "0", "0"])[:4]
nums = tuple(int(p) if p.isdigit() else 0 for p in parts)
YEAR = 2026

TEMPLATE = f"""# Auto-generated by packaging/make_version_info.py -- do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={nums},
    prodvers={nums},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', {PUBLISHER!r}),
        StringStruct('FileDescription', {APP_NAME!r}),
        StringStruct('FileVersion', {__version__!r}),
        StringStruct('InternalName', 'TankMonitorConsoleSimulator'),
        StringStruct('LegalCopyright',
                     'Copyright (C) {YEAR} {PUBLISHER}. GNU GPL v3.'),
        StringStruct('OriginalFilename',
                     'TankMonitorConsoleSimulator.exe'),
        StringStruct('ProductName', {APP_NAME!r}),
        StringStruct('ProductVersion', {__version__!r}),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main():
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "version_info.txt")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(TEMPLATE)
    print(f"wrote {out}  ({__version__})")


if __name__ == "__main__":
    main()
