# Tank Monitor Console Simulator -- a training simulator for TLS-350
# compatible tank monitor consoles.
# Copyright (C) 2026 Verbose Software
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. It is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License (LICENSE) for more details.
"""The LINE LEAK function codes: volumetric, pressure and wireless pressure.

Section 7.2.4 of the Serial Interface Manual is the reports a site asks for,
351 to 389, and section 7.4.4 is the diagnostics a technician asks for, B50 to
B8E. They are the same three line types read at two depths, so they live in
one module: 351/352/353 and B50/B51/B52 are the volumetric controller, 373 to
384 and B7B/B7C/B7E/B81/B87/B88/B89/B8A are PLLD, and 386 to 389 with
B7D/B7F/B82/B83/B8B/B8C/B8D/B8E are WPLLD.

Every layout here is the manual's own, read from BOTH blocks each section
prints: the "Typical Response Message, Display Format" that a printer gets and
the "Typical Response Message, Computer Format" that a host gets. Where the
two disagree about which rate comes first, the manual is followed rather than
tidied, because a host parses the computer format and a tidy console is a
console a host cannot read. 373 and 374 are the case: their displays print
0.20 above 0.10, and their notes number the fields the other way round,
"NN - Number of 0.10 gal/hr test results ... nn - Number of 0.20 gal/hr test
results". WPLLD's 388 and 389 are consistent the other way, 0.20 first in both.

READING THE MANUAL'S SAMPLE PRINTOUTS

The sample printouts are two-column, and a plain-text extraction interleaves
them: the right-hand column lands on the wrong line. 382's sample reads

    Q 1:REGULAR UNLEADED    JAN 9, 1995 6:12 AM
           GROSS LINE FAIL

which is a date with no report line and a report line with no date; the
console prints a date and its alarm on one row, which the 352 sample gives
away by having three dates and two alarm texts. The same shift puts 351's
"PUMP" column heading on the label line, B81's sensor count on the "A/D
COUNTS" heading, and B7E's "DAYS" twice at the top of a block whose two
LAST UPDATE lines both end in days. So the rows below are the manual's
columns put back on their own rows, and nothing else.

WHAT IS DERIVED

The pressure reports read `pressure.py`: a Line already holds every quantity
they print. B81's four floats are its pressure and the three A/D counts its
"SNS CNTS should always be in between the LO and HI reference counts" screen
shows. B87 and B88's pass, fail and high-pressure blocks are `Line.readings`,
which the console's own 3.0 DIAG printout groups the same way. B89 and B8A are
`Line.cycles`, whose ratio "Ratio <1 Pass, >1 Fail" is the whole verdict.
B7E's monitors are the PLLD & WPLLD Troubleshooting Guide's Figure 13, whose
terms it defines: "P0 = Line pressure w/pump off (< 5 psi), Pd = Pump pressure
during dispense, Pv = Pump vent pressure", with "Pv = P2 measured in last
gross test" and "Pon = pump on pressure measured in last gross test".

B7B is entirely programmed data: the seven floats it reports are functions
775, 776, 777, 778, 779, 789 and 77F, which are the profile line test's own
setup codes, so a console that has been programmed reports what it was told
and one that has not falls back to the pipe table in `pressure.py`.

The volumetric reports read `leaktest.py`, because a VLLD test is a stopwatch
over a result rather than a pressure curve. 351's three columns are grounded
in the Operator's Manual: "A Self test checks for improper switch conditions
throughout the Line Leak test. It also includes a Pumpside Pressure test and
Self test (if enabled during setup)." So a passed line test carries a passed
self test with it, and the pumpside column counts only where S758 says
PUMPSIDE TEST: ENABLED.

WHAT IS GENERATED, AND WHY IT IS SAID SO

Three things the manual reports have no model behind them, and each is
generated by `readings.py`'s rule: stable per device, plausible for the
hardware, and never random.

B51 and B52's switch timings and temperatures - "Allowed tenths of a second
for Final Switch to actuate", "Tenths of a second for Start Switch to close",
"Ground Temp dispenser off" - are a mechanical leak detector's own numbers,
and this simulator has no mechanical leak detector; it has a result. They are
generated in the bands the manual's own sample prints.

B50's eight switch and valve states are derived from whether a test is running
and whether the line is disabled, which are real, but the mapping from those
to eight signals is the simulator's own and is marked where it is made.

B7E's "last update in days" counters are the time since a line last sat below
5 psi and the time since Pd was last inside Pd Ref + 5 psi. Neither is logged
here, so they are generated stable per line, in the range the guide's own
figure prints (21 and 51 days) and against the threshold it gives, "If longer
than 30 days, Pd state will be a fail".
"""
import math
import time

from . import packed
from . import leaktest
from . import pressure
from . import readings
from .clock import clock_words
from .console import describe_alarms

# "display format ... includes all the necessary formatting characters such as
# carriage returns, line feeds". Defined here rather than imported from
# wire.py, which imports this module.
SEP = chr(13) + chr(10)

# "Q" for a PLLD line, "W" for a WPLLD one, "P" for a volumetric one, as every
# sample in this section heads its lines.
LETTER = {"plld": "Q", "wplld": "W", "vlld": "P"}

# each line type's location label function
LABEL = {"plld": "782", "wplld": "7A2", "vlld": "760"}

# each line type's alarm category in i10100's own table
CATEGORY = {"plld": "21", "wplld": "26", "vlld": "06"}

# Which module has to be fitted before the console has heard of the code.
KIND = {
    "351": "vlld", "352": "vlld", "353": "vlld",
    "B50": "vlld", "B51": "vlld", "B52": "vlld",
    "373": "plld", "374": "plld", "381": "plld", "382": "plld",
    "383": "plld", "384": "plld",
    "B7B": "plld", "B7C": "plld", "B7E": "plld", "B81": "plld",
    "B87": "plld", "B88": "plld", "B89": "plld", "B8A": "plld",
    "386": "wplld", "387": "wplld", "388": "wplld", "389": "wplld",
    "B7D": "wplld", "B7F": "wplld", "B82": "wplld", "B83": "wplld",
    "B8B": "wplld", "B8C": "wplld", "B8D": "wplld", "B8E": "wplld",
}

CODES = set(KIND)

# Section 7.2's reports print the station header and section 7.4's diagnostics
# do not: every 351 to 389 sample carries "STATION HEADER 1...." through
# "STATION HEADER 4...." under the date, and no B-code sample has one.
HEADED = {"351", "352", "353", "373", "374", "381", "382", "383", "384",
          "386", "387", "388", "389"}

# "tt - Test status" as 381, 383 and B81 number it, which is the console's own
# STATUS_CODE table in pressure.py. The words are the manual's own note text,
# because this report writes "TESTING 0.10 GAL/HR" where the diagnostic screen
# writes "TEST 0.10".
PLLD_STATUS = {"00": "TEST COMPLETE", "01": "DISPENSING",
               "02": "TESTING 3.00 GAL/HR", "03": "TESTING 0.10 GAL/HR",
               "04": "TEST ABORTED", "05": "RUNNING PUMP",
               "06": "LINE LOCKOUT", "07": "DISABLE ALARM",
               "08": "TEST PENDING", "09": "TEST DELAY",
               "0A": "PRESSURE CHECK", "0B": "TESTING 0.20 GAL/HR"}

# WPLLD numbers the same nine states DIFFERENTLY, and 386, B82 and B83 all
# print its table rather than PLLD's: "03=testing at 0.20 gal/hr,
# 04=test aborted, 05=line lockout, 06=disable alarm, 07=test pending,
# 08=test delay, 09=testing at 0.10 gal/hr". There is no code for running pump
# or pressure check, so those report as the test they are part of.
WPLLD_STATUS_CODE = {"TEST COMPLETE": "00", "DISPENSING": "01",
                     "TEST 3.0": "02", "TEST 0.20": "03",
                     "TEST ABORTED": "04", "LINE LOCKOUT": "05",
                     "DISABLE ALARM": "06", "TEST PENDING": "07",
                     "TESTING DELAY": "08", "TEST 0.10": "09",
                     "RUNNING PUMP": "02", "PRESSURE CHECK": "02"}
WPLLD_STATUS = {"00": "TEST COMPLETE", "01": "DISPENSING",
                "02": "TESTING 3.00 GAL/HR", "03": "TESTING 0.20 GAL/HR",
                "04": "TEST ABORTED", "05": "LINE LOCKOUT",
                "06": "DISABLE ALARM", "07": "TEST PENDING",
                "08": "TEST DELAY", "09": "TESTING 0.10 GAL/HR"}

# B7B note 6's pipe list, which is the same enumeration `pressure.PIPE` is
# keyed by. "18=User Defined" is the one that changes what B89 prints.
PIPE_NAME = {
    "01": '2.0"/3.0" FIBERGLASS', "02": '2.0" STEEL',
    "03": "WHITE ENVIROFLEX PP1501", "04": '1.5" ENVIRON GEOFLEX II',
    "05": "OMNIFLEX CP1501", "06": "YELLOW ENVIROFLEX PP1500",
    "07": '1.5"/2.5" ENVIROFLEX PP1502/2502', "08": "OPW PISCES SP-15",
    "09": "OPW PISCES CP-15", "10": "WFG COFLEX 2000 RIBBED",
    "11": "ENVIROFLEX PP1503/2503", "12": "OMNIFLEX CP1503",
    "13": '1.5"/2.0" ENVIRON GEOFLEX D', "14": "APT P175SC",
    "15": "OPW PISCES CP15DW", "16": "OPW PISCES CP20",
    "17": "OPW PISCES SP20", "18": "USER  DEFINED",
    "19": "PETROTECHNIK UPP EXTRA 63MM",
}
USER_DEFINED = "18"

# "Numbers in "TYP" column above and "TT" below refer to 0.20 GPH tests (7-10)
# or 0.10 GPH tests (11-14)", and B51's own sample uses 3 to 6 for the gross
# tests. Four codes per rate, and i10100 names exactly four VLLD tests per
# rate: Line Test, Line Selftest, Pump Test, Pump Selftest. So the first of
# each quartet is the line test, which is the one this simulator runs.
VLLD_LINE_TEST = {"gross": 3, "periodic": 7, "annual": 11}

# "RR - Test result (00=fail, 01=pass)" in 351, which is NOT the console's
# usual RESULT_CODE and is not shared with any other report here.
VLLD_PASS_FAIL = {leaktest.PASSED: "01"}

# "RR - Test Result: 00=Pass, 01=Fail" in B89, B8A, B8D and B8E, and
# "RR - Test result type: 00=Pass, 01=Fail, 02=Hi-pressure events" in B87,
# B88, B8B and B8C. The diagnostics count from zero where the reports count
# from one.
DIAG_PASS, DIAG_FAIL, DIAG_HIGH = "00", "01", "02"

# "P 0:-99.000 PSI": what B82 prints in a sample slot that holds no reading.
NO_READING = -99.000

# "P0 = Line pressure w/pump off (< 5 psi)", the pressure below which the
# guide says "it is known that pressure transducer has little or no offset".
OFFSET_CLEAR = 5.0

# "If Pd > Pd ref by more than 5 psi for 30 days LN EQ FAULT alarm posted",
# and Figure 13: "If longer than 30 days, Pd state will be a fail".
PD_MARGIN = 5.0
PD_DAYS = 30.0

# "If Pv > 40 psi and Pd > 50 psi -> Line Equipment Fault alarm is posted."
PV_LIMIT, PD_LIMIT = 40.0, 50.0


# ---------------------------------------------------------------------------
# the small change every report spends
# ---------------------------------------------------------------------------
# "ASCII Hex IEEE float", which is how this manual writes every number. One
# encoder, in packed, under the name this module already calls it by.
_float = packed.hexfloat


def _stamp(when):
    """YYMMDDHHmm, or the manual's own ""0000000000" if no test yet"."""
    if not when:
        return "0000000000"
    return time.strftime("%y%m%d%H%M", time.localtime(when))


def _words(packed):
    """A packed stamp as the display format writes it, "DEC 22, 1995  3:31 PM"."""
    try:
        return clock_words(time.strptime(packed, "%y%m%d%H%M"))
    except ValueError:
        return packed


def _head(console, kind, number):
    """"Q 1:REGULAR UNLEADED", the line every one of these reports opens with."""
    label = console.text(LABEL[kind], number) or ""
    return f"{LETTER[kind]} {number}:{label}".rstrip()


def _display(handler, code, rows, tok):
    """The display format, with the station header where the manual shows one."""
    text = SEP.join(rows)
    if tok in HEADED:
        header = [t for t in (handler.c.text("503", n) for n in range(1, 5))
                  if t]
        if header:
            text = SEP.join(header) + SEP + text
    return handler._frame(code, text)


def _midnight(console):
    """The console's own midnight, which is what "SINCE MIDNIGHT" counts from."""
    t = console.now()
    return time.mktime((t.tm_year, t.tm_mon, t.tm_mday, 0, 0, 0, 0, 1, -1))


def _passes(console, kind, number, rate_key, since):
    """How many tests at that rate have passed on that line since then."""
    log = console.leaks.history.get((kind, number)) or []
    return sum(1 for r in log if r.rate_key == rate_key
               and r.result == leaktest.PASSED and r.started >= since)


def _alarms(console, kind, number, log):
    """The alarms standing against, or logged against, one line.

    "aaaa - type of alarm" is i10100's list numbered in hex where i10100
    numbers it in decimal, which is the same relation I206 has to it: PLLD
    Gross Test Fail Alarm is 21/02 on one and 0002 on the other.
    """
    want = CATEGORY[kind]
    if log:
        return [r for r in console.alarm_log
                if r["aa"] == want and r["tt"] == f"{number:02d}"]
    return [r for r in console.compute_alarms()
            if r[:2] == want and r[4:6] == f"{number:02d}"]


def _alarm_code(nn):
    return f"{int(nn):04X}" if nn.isdigit() else "0000"


def _alarm_text(aa, nn):
    return describe_alarms([aa + nn + "01"])[0]["description"].upper()


def _status_bits(console, ln, kind, number):
    """"SSSS - Status Bits", the three the manual defines and thirteen unused.

    "Bit 1 - (LSB) Dispensing enabled flag (0=Disabled, 1=Enabled), Bit 2 -
    Pump power (0=Pump Off, 1=Pump On), Bit 3 - Dispenser Handle (0=Handle
    Off, 1=Handle On)."
    """
    bits = 0
    if (kind, number) not in console.leaks.disabled:
        bits |= 1
    if ln.pump:
        bits |= 2
    if ln.handle:
        bits |= 4
    return f"{bits:04X}"


def _test_status(ln, kind):
    """(tt, the words that go with it) in whichever of the two tables applies."""
    if kind == "wplld":
        tt = WPLLD_STATUS_CODE.get(ln.status(), "00")
        return tt, WPLLD_STATUS[tt]
    tt = ln.status_code()
    return tt, PLLD_STATUS.get(tt, "TEST COMPLETE")


def _dispensing(console, kind, number):
    """"DISPENSING" column: what the shutdown output is doing to the line."""
    return "DISABLED" if (kind, number) in console.leaks.disabled else "ENABLED"


def _line_row(console, ln, kind, number):
    """One row of the status table 381, 386, B81 and B82 all share."""
    _tt, words = _test_status(ln, kind)
    return (f"{_head(console, kind, number):<25.25s}"
            f"{_dispensing(console, kind, number):<12s}{words:<22s}"
            f"{'ON' if ln.pump else 'OFF':<6s}"
            f"{'ON' if ln.handle else 'OFF'}")


LINE_HEADER = (f"{'LINE':<25s}{'DISPENSING':<12s}{'TEST STATUS':<22s}"
               f"{'PUMP':<6s}HANDLE")


def _no_vent(ln):
    """"NO-VENT TEST ABORTS: 3 OUT OF 10 TESTS".

    "Test aborts if Pon = P1 (P1 should be lower since pump is shut off before
    P1 is measured)", so the count is every measurement whose Pon and P1 came
    out the same. 373 and 388 print one figure for the line rather than one
    per rate, so every measurement the line holds is counted.
    """
    rows = (ln.readings["gross"] + ln.readings["mid"]
            + ln.cycles["periodic"] + ln.cycles["annual"])
    return sum(1 for r in rows if abs(r.pon - r.p1) < 0.001), len(rows)


def _result_word(result):
    """"JAN 24, 1996 2:49 PM PASS", which is how these reports print a verdict."""
    if result is None:
        return "NO TEST DATA AVAILABLE"
    word = {leaktest.PASSED: "PASS", leaktest.FAILED: "FAIL"}.get(
        result.result, "INVALID")
    return f"{clock_words(result.started)} {word}"


# ---------------------------------------------------------------------------
# 7.2.4, the volumetric line leak reports
# ---------------------------------------------------------------------------
def _pumpside(console, number):
    """S758: "PUMPSIDE TEST: ENABLED", "ss - 01=Enable"."""
    raw = (console.values.get(f"S758{number:02d}") or "").strip()
    return raw.endswith("1")


def _recent(console, number, rate_key, most=3):
    """The precision tests 351 lists, newest first.

    The manual's sample prints three dates under each rate and its computer
    format carries a count, so three is the depth the report is drawn at.
    """
    log = console.leaks.history.get(("vlld", number)) or []
    return [r for r in reversed(log) if r.rate_key == rate_key][:most]


def _vlld_results(handler, code, kind, lines, tok):
    """351: the 3.0 counts in three columns, then the precision test dates.

    "LL - 3.00 GPH Line tests passed in previous 24 hours", "SS - 3.00 GPH
    Self tests passed", "BB - 3.00 GPH Pumpside tests passed", then the same
    three since midnight.

    The self test is not a test of its own: "A Self test checks for improper
    switch conditions THROUGHOUT the Line Leak test", so it passes whenever
    the line test it rode on passed, and deriving it is correct.

    The pumpside test is NOT derived, and used to be. It measures "the piping
    and connections between the in-line check valve and the submersible
    pump", which is a different piece of pipe from the one the line test just
    measured, so its count comes from its own results. A line that passes
    over a leaking pump-side joint reports LINE 1 PUMP 0, which is the whole
    reason the test exists.
    """
    c = handler.c
    now = time.mktime(c.now())
    windows = (now - 86400.0, _midnight(c))
    rows, body = [], ""
    for number in lines:
        counts = []
        for since in windows:
            line = _passes(c, "vlld", number, "gross", since)
            pump = c.leaks.pumpside_passes(number, "gross", since)
            counts.append((line, line, pump))
        periodic = _recent(c, number, "periodic")
        annual = _recent(c, number, "annual")
        rows.append(_head(c, "vlld", number))
        rows.append(f"{'3.0 GAL/HR TEST':<27s}{'LINE':>5s}{'SELF':>6s}"
                    f"{'PUMP':>6s}")
        for name, (line, self_, pump) in zip(("PREV 24 HOURS",
                                              "SINCE MIDNIGHT"), counts):
            rows.append(f"           {name:<16s}{line:5d}{self_:6d}{pump:6d}")
        for name, results in (("0.2 GAL/HR TEST", periodic),
                              ("0.1 GAL/HR TEST", annual)):
            rows.append(name)
            for r in results:
                rows.append(f"           {clock_words(r.started):<24s}"
                            f"{r.result}")
            if not results:
                rows.append("           NO TEST DATA AVAILABLE")
        body += f"{number:02d}"
        for line, self_, pump in counts:
            body += f"{min(line, 255):02X}{min(self_, 255):02X}" \
                    f"{min(pump, 255):02X}"
        for results in (periodic, annual):
            body += f"{len(results):02d}"
            for r in results:
                body += _stamp(r.started) + VLLD_PASS_FAIL.get(r.result, "00")
    if code[0].isupper():
        return _display(handler, code, rows, tok), "volumetric line results"
    return handler._frame(code, body), "volumetric line results"


def _line_alarm_history(handler, code, kind, lines, tok):
    """352, 382 and 387: every alarm this line has raised, with its date.

    "NN - Number of Alarm entries to follow (Decimal)" in 352 and
    "NN - number of alarms to follow (Hex)" in 382 and 387, which is the same
    two characters for any count a console keeps.
    """
    c = handler.c
    titles = {"352": "", "382": "PRESSURE LINE LEAK ALARM HISTORY REPORT",
              "387": "WPLLD LINE LEAK ALARM HISTORY REPORT"}
    rows = [titles[tok], ""] if titles[tok] else []
    body = ""
    for number in lines:
        records = _alarms(c, kind, number, log=True)
        rows.append(_head(c, kind, number))
        for r in records:
            rows.append(f"   {_words(r['at']):<22s}"
                        f"{_alarm_text(r['aa'], r['nn'])}")
        if not records:
            rows.append("   NO ALARM HISTORY")
        rows.append("")
        count = (f"{len(records):02d}" if tok == "352"
                 else f"{min(len(records), 255):02X}")
        body += f"{number:02d}{count}"
        body += "".join(r["at"] + _alarm_code(r["nn"]) for r in records)
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line alarm history"
    return handler._frame(code, body), "line alarm history"


def _vlld_pump_status(handler, code, kind, lines, tok):
    """353: "aaaa - Line Status: 0001=Enabled, 0002=Disabled"."""
    c = handler.c
    rows = [f"{'LINE':<11s}{'LOCATION':<22s}STATUS"]
    body = ""
    for number in lines:
        down = ("vlld", number) in c.leaks.disabled
        label = c.text(LABEL["vlld"], number) or ""
        rows.append(f"{number:5d}      {label:<22.22s}"
                    + ("DISABLED" if down else "ENABLED"))
        body += f"{number:02d}" + ("0002" if down else "0001")
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line pump status"
    return handler._frame(code, body), "line pump status"


# ---------------------------------------------------------------------------
# 7.2.4, the pressure line leak reports
# ---------------------------------------------------------------------------
# Which rates each results and history report carries, and in which order the
# COMPUTER format carries them, which is not the display's order for PLLD:
# 373 and 374 count "NN - Number of 0.10 gal/hr test results" before
# "nn - Number of 0.20 gal/hr test results" and print the two the other way
# up, where 388 and 389 are 0.20 first in both halves.
RESULT_RATES = {"373": ("annual", "periodic"), "383": ("annual",),
                "388": ("periodic", "annual"),
                "374": ("annual", "periodic"), "384": ("annual",),
                "389": ("periodic", "annual")}
SHOWN_RATES = {"373": ("periodic", "annual"), "383": ("annual",),
               "388": ("periodic", "annual")}
RATE_NAME = {"periodic": "0.20", "annual": "0.10"}


def _pressure_results(handler, code, kind, lines, tok):
    """373, 383 and 388: the last test at each rate, and the 3.0 pass counts.

    "PPPP - Number of 3.00 gal/hr tests passed in previous 24 hours (Hex)"
    over "MMMM - Number of 3.00 gal/hr tests passed since midnight (Hex)",
    then a count and a group of fourteen characters for each precision result,
    "RR - Test result 01=PASS 02=FAIL" and "tt - test type (unused, always
    00)".

    383 is the same report with the 0.20 block taken out, and its own note
    says why it exists: "In Version 12, this command's response is
    inadvertently identical to I373QQ. In Versions 7-11, 14, and higher, the
    response is accurately defined here."
    """
    c = handler.c
    now = time.mktime(c.now())
    title = ("WPLLD LINE LEAK TEST RESULTS" if kind == "wplld"
             else "PRESSURE LINE LEAK TEST RESULTS")
    rows, body = [title, ""], ""
    for number in lines:
        ln = c.lines.line(kind, number)
        gross = c.leaks.result(kind, number, "gross")
        day = _passes(c, kind, number, "gross", now - 86400.0)
        since = _passes(c, kind, number, "gross", _midnight(c))
        rows += [_head(c, kind, number), "", "3.0 GAL/HR RESULTS:", "",
                 "LAST TEST:", _result_word(gross), "",
                 "NUMBER OF TESTS PASSED", f"   PREV 24 HOURS : {day}", "",
                 f" SINCE MIDNIGHT : {since}", ""]
        for rate_key in SHOWN_RATES[tok]:
            rows.append(f"{RATE_NAME[rate_key]} GAL/HR RESULTS:")
            rows.append("")
            rows.append(_result_word(c.leaks.result(kind, number, rate_key)))
            rows.append("")
        if tok != "383":
            # "NO-VENT TEST ABORTS: 3 OUT OF 10 TESTS (Added in V19)", which
            # 383's own sample does not print
            aborts, total = _no_vent(ln)
            rows.append("NO-VENT TEST ABORTS:")
            rows.append(f"   {aborts} OUT OF {total} TESTS")
            rows.append("")
        body += (f"{number:02d}{_stamp(gross.started if gross else 0)}"
                 + (leaktest.RESULT_CODE[gross.result] if gross else "00")
                 + "00" + f"{min(day, 0xFFFF):04X}{min(since, 0xFFFF):04X}")
        for rate_key in RESULT_RATES[tok]:
            result = c.leaks.result(kind, number, rate_key)
            body += "01" if result else "00"
            if result:
                body += (_stamp(result.started)
                         + leaktest.RESULT_CODE[result.result] + "00")
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line leak test results"
    return handler._frame(code, body), "line leak test results"


def _pressure_history(handler, code, kind, lines, tok):
    """374, 384 and 389: the last 3.0 pass, and the first precision pass a month.

    "yymmddhhmm - Last 3.00 gal/hr test pass time ("0000000000" if no test
    yet)", then a count and twelve characters for each month's first pass.
    Twelve rather than fourteen because a history entry carries no result:
    every date in it is a pass.
    """
    c = handler.c
    title = ("WPLLD LINE LEAK TEST HISTORY" if kind == "wplld"
             else "PRESSURE LINE LEAK TEST HISTORY")
    rows, body = [title, ""], ""
    for number in lines:
        last = c.leaks.last_pass(kind, number, "gross")
        rows += [_head(c, kind, number), "",
                 f"{'LAST 3.0 PASS:':<28s}"
                 + (clock_words(last) if last else "NO PASS RECORDED"), ""]
        body += f"{number:02d}{_stamp(last)}00"
        for rate_key in RESULT_RATES[tok]:
            months = c.leaks.first_pass_each_month(kind, number, rate_key)
            head = f"FIRST {RATE_NAME[rate_key]} PASS EACH MONTH:"
            rows.append(f"{head:<28s}"
                        + (clock_words(months[0]) if months
                           else "NO PASS RECORDED"))
            for when in months[1:]:
                rows.append(" " * 28 + clock_words(when))
            rows.append("")
            body += f"{min(len(months), 255):02X}"
            body += "".join(_stamp(w) + "00" for w in months)
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line leak test history"
    return handler._frame(code, body), "line leak test history"


def _line_status(handler, code, kind, lines, tok):
    """381 and 386: the status table, then the alarms standing against it.

    "NN - number of active alarms to follow (Hex)" and "aaaa - type of alarm",
    which is why the display ends "ACTIVE ALARMS:" with nothing under it on a
    line that has none.
    """
    c = handler.c
    title = ("WPLLD LINE LEAK STATUS" if kind == "wplld"
             else "PRESSURE LINE LEAK STATUS")
    rows, body, standing = [title, "", LINE_HEADER], "", []
    for number in lines:
        ln = c.lines.line(kind, number)
        rows.append(_line_row(c, ln, kind, number))
        records = _alarms(c, kind, number, log=False)
        standing += records
        tt, _words_ = _test_status(ln, kind)
        body += (f"{number:02d}{_status_bits(c, ln, kind, number)}{tt}"
                 f"{min(len(records), 255):02X}")
        body += "".join(_alarm_code(r[2:4]) for r in records)
    rows += ["", "ACTIVE ALARMS:"]
    rows += ["     " + _alarm_text(r[:2], r[2:4]) for r in standing]
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line leak status"
    return handler._frame(code, body), "line leak status"


# ---------------------------------------------------------------------------
# 7.4.4, the volumetric line leak diagnostics
# ---------------------------------------------------------------------------
def _vlld_tank(console, number):
    """S752, "Set Volumetric Line Leak Tank Number"."""
    raw = (console.values.get(f"S752{number:02d}") or "").strip()
    body = raw[2:] if len(raw) > 2 else raw
    return int(body) if body.isdigit() else 0


def _vlld_switches(console, number):
    """The eight signals B50 draws, from the two things the model knows.

    THE MAPPING IS THE SIMULATOR'S OWN. What is real is whether a test is
    running and whether the line has been shut down; a volumetric controller's
    switches are not modelled anywhere in this simulator, because a VLLD test
    here is a stopwatch over a result rather than a mechanical detector.

    The mapping is the one the manual's own sample implies. Its line is idle
    and disabled, and reads PMP IN=OFF PMP OUT=OFF, PRS SW=ON, EQU VLV=OFF,
    FIN SW=OFF, TST VLV=OFF, STR SW=ON, DISABLE=ON: so at rest the line holds
    pressure and the start switch is made, the pump signals and both valves
    are off, and DISABLE follows the shutdown.
    """
    running = console.leaks.active("vlld", number) is not None
    down = ("vlld", number) in console.leaks.disabled
    pump_in = running
    pump_out = running and not down
    return {"pump_in": pump_in, "pressure": True, "final": running,
            "start": True, "pump_out": pump_out, "equalise": running,
            "test": running, "disable": down}


def _on(flag):
    """" ON" or "OFF", right aligned in three, as the B50 screen draws them."""
    return " ON" if flag else "OFF"


def _vlld_status(handler, code, kind, lines, tok):
    """B50: four rows of two signals each, in the order the notes number them."""
    c = handler.c
    rows, body = [], ""
    for number in lines:
        s = _vlld_switches(c, number)
        rows.append(_head(c, "vlld", number))
        rows.append(f"   PMP IN={_on(s['pump_in'])} "
                    f"PMP OUT={_on(s['pump_out'])}")
        rows.append(f"   PRS SW={_on(s['pressure'])} "
                    f"EQU VLV={_on(s['equalise'])}")
        rows.append(f"   FIN SW={_on(s['final'])} "
                    f"TST VLV={_on(s['test'])}")
        rows.append(f"   STR SW={_on(s['start'])} "
                    f"DISABLE={_on(s['disable'])}")
        rows.append("")
        body += f"{number:02d}"
        for key in ("pump_in", "pressure", "final", "start", "pump_out",
                    "equalise", "test", "disable"):
            body += "01" if s[key] else "00"
    if code[0].isupper():
        return _display(handler, code, rows, tok), "volumetric line status"
    return handler._frame(code, body), "volumetric line status"


def _vlld_timings(console, number, result):
    """The six columns B51 and B52 print that this simulator does not model.

    GENERATED, per readings.py's rule: stable per line and per test, in the
    bands the manual's own samples print. "DDDD - Minutes since dispenser off"
    runs 0 to 81 across the two samples, "LLLL - Allowed tenths of a second for
    Final Switch to actuate" 10.0 to 794.0, "RRRR - Tenths of a second for
    Start Switch to close" 0.0 to 4.9, and "TTTT - Actual tenths of a second
    for Final Switch to actuate" 5.3 to 326.0. The actual can never exceed the
    allowed on a test that passed, which is what the allowance is for.

    The two temperatures are not generated: the tank's is the probe's own
    reading for the tank this line is programmed to, and the ground sits a
    little above it, which is the relation both samples show (46.9 over 45.9,
    45.3 over 45.4).
    """
    tank = _vlld_tank(console, number)
    tank_temp = console.product_temperature(tank or number)
    ground = tank_temp + readings.fixed(-1.0, 1.6, "grnd", number)
    key = ("vlld", number, result.started)
    allowed = readings.fixed(10.0, 794.0, "lgth", *key)
    actual = readings.fixed(5.3, 326.0, "final", *key)
    if result.result == leaktest.PASSED:
        actual = min(actual, allowed)
    return (ground, tank_temp,
            readings.integer(0, 81, "dely", *key), allowed,
            readings.fixed(0.0, 4.9, "reset", *key), actual)


def _vlld_diag_history(handler, code, kind, lines, tok):
    """B51 and B52: the gross tests, and the two precision rates.

    Both are the same record, "YYMMDDHHmmTTg..gt..tDDDDLLLLRRRRTTTTrr", and
    differ only in which tests are in it. The TYP column is the manual's own
    quartet numbering, and this simulator runs the line test of each quartet.
    """
    c = handler.c
    wanted = ("gross",) if tok == "B51" else ("periodic", "annual")
    header = (f"{'DATE/TIME':<22s}{'TYP':>3s}{'GRND':>7s}{'TANK':>7s}"
              f"{'DELY':>6s}{'LGTH':>8s}{'RSET':>7s}{'TEST':>8s}  RSLT")
    rows, body = [], ""
    for number in lines:
        log = [r for r in reversed(c.leaks.history.get(("vlld", number)) or [])
               if r.rate_key in wanted]
        rows += [_head(c, "vlld", number), header]
        block = ""
        for r in log:
            typ = VLLD_LINE_TEST[r.rate_key]
            grnd, tank, dely, allowed, reset, actual = _vlld_timings(
                c, number, r)
            rows.append(f"{clock_words(r.started):<22s}{typ:3d}{grnd:7.1f}"
                        f"{tank:7.1f}{dely:6d}{allowed:8.1f}{reset:7.1f}"
                        f"{actual:8.1f}  {r.result}")
            # the wire's timings are a 16-bit count of tenths of a second
            # where the printout carries a decimal place, so they round
            block += (_stamp(r.started) + f"{typ:02X}" + _float(grnd)
                      + _float(tank) + f"{min(dely, 0xFFFF):04X}"
                      + f"{round(allowed):04X}{round(reset):04X}"
                      + f"{round(actual):04X}"
                      + leaktest.RESULT_CODE[r.result])
        if not log:
            rows.append("NO TEST DATA AVAILABLE")
        rows.append("")
        body += f"{number:02d}{len(log):02d}" + block
    if code[0].isupper():
        return _display(handler, code, rows, tok), "volumetric line diagnostic"
    return handler._frame(code, body), "volumetric line diagnostic"


# ---------------------------------------------------------------------------
# 7.4.4, the pressure line leak diagnostics
# ---------------------------------------------------------------------------
def _diameter(gallons_per_foot):
    """Inches, from the gallons a foot of that pipe holds.

    A gallon is 231 cubic inches, so a foot of pipe holding g gallons has a
    bore of 231g/12 square inches, and the diameter follows. The Application
    Guide publishes the volume rather than the bore, so this is the bore it
    published: 0.190 gal/ft comes back as 2.16 inches, which is 2 inch pipe.
    """
    area = 231.0 * gallons_per_foot / 12.0
    return math.sqrt(4.0 * area / math.pi)


def _pipe_key(console, kind, number):
    """The S788 piping-material enumeration this line is programmed with."""
    code = "788" if kind == "plld" else "7A8"
    raw = (console.values.get(f"S{code}{number:02d}") or "").strip()
    return raw[-2:] if len(raw) >= 2 else pressure.DEFAULT_PIPE


def _profile_line_test(handler, code, kind, lines, tok):
    """B7B: the seven floats the profile line test leaves behind.

    Every one of them has a setup function of its own, so this reports what
    the console was told rather than anything it invented: 779 Primary Pipe
    Bulk Modulus, 775 Profile Line Test Leak Rate, 776 Profile Line Test
    Reference Pressure, 789 Primary Pipe Length, 777 Primary Pipe Diameter,
    77F Secondary Pipe Length and 778 Secondary Pipe Diameter, in the order
    note 6 lists them.

    "a - Valid profile line test flag, 0=profile line test invalid,
    1=profile line test valid": the test's whole output is the bulk modulus it
    measures, so a line with one programmed at 779 has had one and a line
    without has not.
    """
    c = handler.c
    rows, body = ["PRESSURE LINE LEAK PROFILE LINE TEST", ""], ""
    for number in lines:
        ln = c.lines.line(kind, number)
        measured = c.limit("779", number)
        modulus = measured or ln.pipe()[0]
        when = c._commissioned if measured else None
        key = _pipe_key(c, kind, number)
        values = [modulus,
                  c.limit("775", number) or 0.0,
                  c.limit("776", number) or ln.engine.pump_psi(kind, number),
                  c.limit("789", number) or ln.length(),
                  c.limit("777", number) or _diameter(ln.pipe()[1]),
                  c.limit("77F", number) or 0.0,
                  c.limit("778", number) or 0.0]
        rows += [_head(c, kind, number),
                 "LAST PROFILE LINE TEST: "
                 + (clock_words(when) if when else "NONE"),
                 f"BULK MODULUS: {values[0]:.0f} PSI",
                 f"TEST LEAK RATE: {values[1]:.2f} GPH",
                 f"REF PRESSURE: {values[2]:.2f} PSI", "",
                 "TYP:" + PIPE_NAME.get(key, PIPE_NAME[pressure.DEFAULT_PIPE]),
                 f"1ST LINE  LEN :{values[3]:.0f} FEET",
                 f"2ND LINE  LEN :{values[5]:.0f} FEET",
                 f"1ST LINE  DIAM: {values[4]:.2f} IN.",
                 f"2ND LINE  DIAM: {values[6]:.2f} IN.", ""]
        body += (f"{number:02d}" + ("1" if measured else "0") + _stamp(when)
                 + key + f"{len(values):02X}"
                 + "".join(_float(v) for v in values))
    if code[0].isupper():
        return _display(handler, code, rows, tok), "profile line test"
    return handler._frame(code, body), "profile line test"


def _offset_test(handler, code, kind, lines, tok):
    """B7C and B7D: what the last pressure measurement offset test read.

    "In the W/PLLD diagnostic menu, run the Pressure Measurement Offset test
    ... If the test result is greater than 5 psi, check the transducer
    wiring." The console's own P OFFSET TEST screen already reports this, and
    it reports it from `readings`, so this reads the same value off the same
    key: the screen and the wire cannot disagree about one transducer.

    The date is the console's commissioning time, because that is when the
    offset test is done - it is an installation step - and it is the only date
    this model holds for a line. "a - Valid pressure flag": a console that has
    never run has no measurement to report.
    """
    c = handler.c
    title = ("WPLLD LINE LEAK PRESSURE OFFSET TEST" if kind == "wplld"
             else "PRESSURE LINE LEAK PRESSURE OFFSET TEST")
    rows, body = [title, ""], ""
    for number in lines:
        psi = readings.wander(c, -1.8, 1.8, "offset", kind, number, swing=0.15)
        when = c._commissioned
        rows.append(f"{_head(c, kind, number):<38s}"
                    + (clock_words(when) if when else ""))
        rows.append(f"LAST PRESSURE OFFSET TEST: {psi:+.1f} PSI")
        body += (f"{number:02d}" + ("1" if when else "0") + _float(psi)
                 + _stamp(when))
    if code[0].isupper():
        return _display(handler, code, rows, tok), "pressure offset test"
    return handler._frame(code, body), "pressure offset test"


def _offset_monitor(handler, code, kind, lines, tok):
    """B7E and B7F: the three monitors of Figure 13 of 577013-344.

    Its terms are the guide's own: "P0 = Line pressure w/pump off (< 5 psi),
    Pd = Pump pressure during dispense, Pv = Pump vent pressure", and
    "Pv = P2 measured in last gross test" over "Pon = pump on pressure
    measured in last gross test".

    "The PO state will always be pass." Pd fails when it has stood more than
    Pd Ref + 5 psi for longer than thirty days, and Pv fails on the vent
    pressure monitor's own rule, "If Pv > 40 psi and Pd > 50 psi".

    The two day counters are GENERATED: nothing here logs when a line last sat
    below 5 psi or when Pd last came back inside its reference, and the guide
    prints 21 and 51 days for them.
    """
    c = handler.c
    title = ("WPLLD LINE LEAK PRESSURE OFFSET MONITORS REPORT"
             if kind == "wplld"
             else "PRESSURE LINE LEAK PRESSURE OFFSET MONITORS REPORT")
    rows, body = [title, ""], ""
    for number in lines:
        ln = c.lines.line(kind, number)
        # Pd Ref is "locked into" the pump's own pressure at startup, so it is
        # this line's nominal, and Pd is what the pump is reading now.
        reference = c.limit("7B7", number) or readings.fixed(
            pressure.PUMP_PSI - 4.0, pressure.PUMP_PSI + 6.5,
            "pump", kind, number)
        pd = c.lines.pump_psi(kind, number)
        last = (ln.readings["gross"] or [None])[-1]
        pv = last.p2 if last else 0.0
        pon = last.pon if last else 0.0
        p0_days = readings.integer(0, 60, "p0days", kind, number)
        pd_days = (0 if pd <= reference + PD_MARGIN
                   else readings.integer(0, 60, "pddays", kind, number))
        pd_ok = pd_days <= PD_DAYS
        pv_ok = not (pv > PV_LIMIT and pd > PD_LIMIT)
        rows += [_head(c, kind, number),
                 "   P0: PASS",
                 f"       LAST UPDATE: {p0_days}     DAYS",
                 "   Pd: " + ("PASS" if pd_ok else "FAIL"),
                 f"       LAST UPDATE: {pd_days}     DAYS",
                 f"       Pd= {pd:.1f} PSI",
                 f"       Pd Ref={reference:.1f} PSI",
                 "   Pv: " + ("PASS" if pv_ok else "FAIL"),
                 f"       Pv ={pv:.1f} PSI",
                 f"       Pon={pon:.1f} PSI",
                 f"       Pd ={pd:.1f} PSI", ""]
        body += (f"{number:02d}01{min(p0_days, 0xFFFF):04X}"
                 + ("01" if pd_ok else "00")
                 + f"{min(pd_days, 0xFFFF):04X}" + _float(pd)
                 + _float(reference) + ("01" if pv_ok else "00")
                 + _float(pv) + _float(pon) + _float(pd))
    if code[0].isupper():
        return _display(handler, code, rows, tok), "pressure offset monitors"
    return handler._frame(code, body), "pressure offset monitors"


def _plld_diagnostic(handler, code, kind, lines, tok):
    """B81: the status row, the pressure, and the transducer's A/D counts.

    "NN - Number of eight character Data Fields to follow" then "1. Pressure
    sensor reading, 2. A/D low reference counts, 3. A/D high reference counts,
    4. A/D sensor counts", which is exactly what the console's own A/D screen
    shows: "SNS CNTS should always be in between the LO and HI reference
    counts. Also the HI counts should always be less than the LO counts."
    """
    c = handler.c
    rows = ["PRESSURE LINE LEAK DIAGNOSTIC REPORT", "", LINE_HEADER]
    body = ""
    for number in lines:
        ln = c.lines.line(kind, number)
        lo, hi, counts = ln.sensor_counts()
        values = [ln.pressure, lo, hi, counts]
        rows.append(_line_row(c, ln, kind, number))
        rows += [f"{ln.pressure:.3f} PSI", "", "A/D COUNTS",
                 f" LOW REF={lo:9.0f} CNTS",
                 f"HIGH REF={hi:9.0f} CNTS",
                 f"  SENSOR={counts:9.0f} CNTS", ""]
        tt, _ = _test_status(ln, kind)
        body += (f"{number:02d}{_status_bits(c, ln, kind, number)}{tt}"
                 f"{len(values):02X}" + "".join(_float(v) for v in values))
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line leak diagnostic"
    return handler._frame(code, body), "line leak diagnostic"


def _samples(ln, most=14):
    """The pressures B82 lists as P 0 to P13, newest first.

    A WPLLD transducer sends its readings up by radio and the console keeps
    the last of them; the sample printout shows every slot as -99.000, which
    is a console holding none. So the slots are filled from the measurements
    this line has actually taken, newest first, and the rest stay empty.
    """
    out = []
    records = sorted(ln.readings["gross"] + ln.readings["mid"]
                     + ln.cycles["periodic"] + ln.cycles["annual"],
                     key=lambda r: r.when, reverse=True)
    for r in records:
        out += [r.p2, r.p1, r.pon]
        if len(out) >= most:
            break
    return (out + [NO_READING] * most)[:most]


def _wplld_diagnostic(handler, code, kind, lines, tok):
    """B82: the status row, the pressure, and the sample buffer under it.

    "PPPPPPPP - Current Pressure in PSI (ASCII Hex IEEE float)": the computer
    format carries the one pressure and the display carries the fourteen.
    """
    c = handler.c
    rows = ["WPLLD LINE LEAK DIAGNOSTIC REPORT", "", LINE_HEADER]
    body = ""
    for number in lines:
        ln = c.lines.line(kind, number)
        rows.append(_line_row(c, ln, kind, number))
        rows += ["", f"{ln.pressure:.3f} PSI", ""]
        held = _samples(ln)
        for i in range(7):
            rows.append(f"P {i}:{held[i]:.3f} PSI  "
                        f"P{i + 7:2d}:{held[i + 7]:.3f} PSI")
        rows.append("")
        tt, _ = _test_status(ln, kind)
        body += (f"{number:02d}{_status_bits(c, ln, kind, number)}{tt}"
                 + _float(ln.pressure))
    if code[0].isupper():
        return _display(handler, code, rows, tok), "line leak diagnostic"
    return handler._frame(code, body), "line leak diagnostic"


def _wplld_comms(handler, code, kind, lines, tok):
    """B83: what the radio link has dropped, and what is at the far end of it.

    "AAAAAAAA - Checksum error count", "BBBBBBBB - Parity error count", both
    as floats. The two lines under them in the display are the WPLLD's own
    software part number and the date it was built, which is what the
    console's WPLLD LINE LEAK DIAG screen shows in the same place.
    """
    c = handler.c
    rows, body = ["WPLLD LINE LEAK COMMUNICATION REPORT", ""], ""
    created = c.software_info()["created"]
    for number in lines:
        ln = c.lines.line(kind, number)
        # a link with no errors on it is the console's own diagnostic screen,
        # "CRC: 0       PARITY: 0"
        crc, parity = 0.0, 0.0
        rows += [_head(c, kind, number),
                 f"CRC:{crc:.0f}      PARITY:{parity:.0f}",
                 f"#: {c.WPLLD_SOFTWARE}", created, ""]
        tt, _ = _test_status(ln, kind)
        body += (f"{number:02d}{_status_bits(c, ln, kind, number)}{tt}"
                 + _float(crc) + _float(parity))
    if code[0].isupper():
        return _display(handler, code, rows, tok), "wplld communications"
    return handler._frame(code, body), "wplld communications"


# B87 and B8B print three blocks, B88 and B8C two: "RR - Test result type,
# 00=Pass, 01=Fail, 02=Hi-pressure events", and a mid-range test has no
# high pressure event of its own to report.
PUMPOFF_WHICH = {"B87": "gross", "B8B": "gross", "B88": "mid", "B8C": "mid"}


def _pumpoff_diagnostic(handler, code, kind, lines, tok):
    """B87, B88, B8B and B8C: the pump-Off tests, in passes, fails and events.

    "LL - Total Events to follow (Max=5 each)" over three groups of
    "YYMMDDHHmm aaaaaaaa bbbbbbbb cccccccc": the date, "Pump on pressure
    read", "First pressure read" and "Second pressure read", which are Pon,
    P1 and P2 as 577013-344 names them. The console's own 3.0 DIAG printout
    groups the same records the same way: "This report contains the last 5
    test passes, fails, and high pressure events."
    """
    c = handler.c
    which = PUMPOFF_WHICH[tok]
    name = "3.0" if which == "gross" else "MID"
    title = ("WPLLD LINE LEAK DIAGNOSTIC REPORT" if kind == "wplld"
             else "PRESSURE LINE LEAK DIAGNOSTIC REPORT")
    header = (f"{'DATE/TIME':<24s}{'PUMP ON':>9s}{'FIRST READ':>13s}"
              f"{'SECOND READ':>13s}")
    rows, body = [title, ""], ""
    for number in lines:
        ln = c.lines.line(kind, number)
        held = ln.readings[which][-30:]
        blocks = [(DIAG_PASS, f" {name} TEST PASSES",
                   [r for r in held if r.passed and not r.high]),
                  (DIAG_FAIL, f" {name} TEST FAILS",
                   [r for r in held if r.passed is False and not r.high])]
        if which == "gross":
            # "High Pressure Event Thresholds: Pon > 50 psi"
            blocks.append((DIAG_HIGH, f" {name} HI PRESSURE EVENTS",
                           [r for r in held if r.high]))
        rows.append(_head(c, kind, number))
        body += f"{number:02d}"
        for result_type, label, records in blocks:
            records = records[-5:]
            rows += ["", label, header]
            for r in records:
                rows.append(f"{clock_words(r.when):<24s}{r.pon:5.1f} PSI"
                            f"{r.p1:9.1f} PSI{r.p2:9.1f} PSI")
            if not records:
                rows.append("NO TEST DATA AVAILABLE")
            body += f"{result_type}{len(records):02X}"
            body += "".join(_stamp(r.when) + _float(r.pon) + _float(r.p1)
                            + _float(r.p2) for r in records)
        rows.append("")
    if code[0].isupper():
        return _display(handler, code, rows, tok), f"{name.lower()} test diagnostic"
    return handler._frame(code, body), f"{name.lower()} test diagnostic"


PRECISION_WHICH = {"B89": "periodic", "B8D": "periodic",
                   "B8A": "annual", "B8E": "annual"}


def _precision_diagnostic(handler, code, kind, lines, tok):
    """B89, B8A, B8D and B8E: the last ten leak rates, as ratios.

    "LL - Total Tests to follow (Max=10)" then "YYMMDDHHmm RR aaaaaaaa
    bbbbbbbb cccccccc": the date, "00=Pass, 01=Fail", "Pump on pressure read,
    PSI", "Fail ratio" and "Duration (in minutes)". The ratio is the verdict
    on its own, "Ratio <1 Pass, >1 Fail", which is why the report carries it
    instead of the rate.

    "For User Defined Pipe Types PUMP ON will be PMID", so the column heading
    follows the pipe the line is programmed with.
    """
    c = handler.c
    which = PRECISION_WHICH[tok]
    rate = RATE_NAME[which]
    title = ("WPLLD LINE LEAK DIAGNOSTIC REPORT" if kind == "wplld"
             else "PRESSURE LINE LEAK DIAGNOSTIC REPORT")
    rows, body = [title, ""], ""
    for number in lines:
        ln = c.lines.line(kind, number)
        held = ln.cycles[which][-10:]
        pump_on = ("PMID" if _pipe_key(c, kind, number) == USER_DEFINED
                   else "PUMP ON")
        rows += [_head(c, kind, number), f"{rate} TEST RESULTS",
                 f"{'DATE/TIME':<22s}{pump_on:>9s}{'RATIO':>8s}"
                 f"{'DURATION':>10s}  RESULTS"]
        for r in held:
            rows.append(f"{clock_words(r.when):<22s}{r.pon:5.1f} PSI"
                        f"{r.ratio:8.2f}{r.minutes:10d}  "
                        + ("PASSED" if r.passed else "FAILED"))
        if not held:
            rows.append("NO TEST DATA AVAILABLE")
        rows.append("")
        body += f"{number:02d}{len(held):02X}"
        body += "".join(_stamp(r.when)
                        + (DIAG_PASS if r.passed else DIAG_FAIL)
                        + _float(r.pon) + _float(r.ratio) + _float(r.minutes)
                        for r in held)
    if code[0].isupper():
        return _display(handler, code, rows, tok), f"{rate} test diagnostic"
    return handler._frame(code, body), f"{rate} test diagnostic"


# Which function answers each code. Grouped rather than one long if-chain,
# because the three line types ask the same questions of different hardware
# and the reports that share a layout share a function.
REPORTS = {
    "351": _vlld_results,
    "352": _line_alarm_history,
    "353": _vlld_pump_status,
    "373": _pressure_results, "383": _pressure_results,
    "388": _pressure_results,
    "374": _pressure_history, "384": _pressure_history,
    "389": _pressure_history,
    "381": _line_status, "386": _line_status,
    "382": _line_alarm_history, "387": _line_alarm_history,
    "B50": _vlld_status,
    "B51": _vlld_diag_history, "B52": _vlld_diag_history,
    "B7B": _profile_line_test,
    "B7C": _offset_test, "B7D": _offset_test,
    "B7E": _offset_monitor, "B7F": _offset_monitor,
    "B81": _plld_diagnostic,
    "B82": _wplld_diagnostic,
    "B83": _wplld_comms,
    "B87": _pumpoff_diagnostic, "B88": _pumpoff_diagnostic,
    "B8B": _pumpoff_diagnostic, "B8C": _pumpoff_diagnostic,
    "B89": _precision_diagnostic, "B8A": _precision_diagnostic,
    "B8D": _precision_diagnostic, "B8E": _precision_diagnostic,
}


def handle(handler, tok, dev, code, data):
    """Answer one function code, or return None if it is not ours."""
    kind = KIND.get(tok)
    if kind is None:
        return None
    if not handler.c.has(kind):
        # a card that is not in the cage is a function this console does not
        # have, which is the same answer as a function it has never heard of
        return handler._nine(code), f"no {kind} module fitted"
    # "QQ - Pressure Line Leak sensor number (Decimal, 00=All)", and the same
    # note heads every report in this family. "All" is all the lines the
    # console HAS, which is what `programmed_lines` means by one: a PLLD
    # controller takes six transducers and a site that wired two has two
    # lines, and reporting TEST COMPLETE against four pieces of pipe nobody
    # configured is reporting on a site that does not exist.
    #
    # A cage with the card in it and nothing programmed still has to answer,
    # because "a function code that it does not recognize" is not what this
    # is, so it answers on the card's first position, where every one of
    # these reports has a NO TEST DATA AVAILABLE to print.
    if dev != "00" and dev.isdigit() and int(dev):
        lines = [int(dev)]
    else:
        lines = [n for k, n, _label in handler.c.programmed_lines()
                 if k == kind]
        if not lines:
            lines = handler._devices_of(kind, dev)[:1]
    return REPORTS[tok](handler, code, kind, lines, tok)
